apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stripebilling.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "stripebilling.name" . }}
    helm.sh/chart: {{ include "stripebilling.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "stripebilling.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "stripebilling.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          - name: JURL
            value: "{{ .Values.JURL }}"
          - name: JSURL
            value: "{{ .Values.JSURL }}"
          - name: JUSER
            value: "{{ .Values.JUSER }}"
          - name: MHOST
            value: "{{ .Values.MHOST }}"
          - name: MPORT
            value: "{{ .Values.MPORT }}"
          - name: MUSER
            value: "{{ .Values.MUSER }}"
          - name: MPASSWD
            value: "{{ .Values.MPASSWD }}"
          - name: MFROM
            value: "{{ .Values.MFROM }}"
          - name: MSUBJECT
            value: "{{ .Values.MSUBJECT }}"
          - name: STRIPEURL
            value: "{{ .Values.STRIPEURL }}"
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            tcpSocket:
              port: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
