apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "storeng.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "storeng.name" . }}
    helm.sh/chart: {{ include "storeng.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "storeng.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "storeng.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
          - name: ENV
            value: "{{ .Values.ENV }}"
          - name: APIURL
            value: "{{ .Values.APIURL }}"
          - name: MEDIAPATH
            value: "{{ .Values.MEDIAPATH }}"
          - name: THEME
            value: "{{ .Values.THEME }}"
          - name: THEMEREPOURL
            value: "{{ .Values.THEMEREPOURL }}"
          - name: THEME_BRANCH
            value: "{{ .Values.THEME_BRANCH }}"
          - name: GITHUB_USER
            value: "{{ .Values.GITHUB_USER }}"
          - name: GITHUB_PASS
            value: "{{ .Values.GITHUB_PASS }}"
          - name: FBAPPID
            value: "{{ .Values.FBAPPID }}"
          - name: GOOGLECLIENTID
            value: "{{ .Values.GOOGLECLIENTID }}"
          - name: GOOGLEANALYTICSID
            value: "{{ .Values.GOOGLEANALYTICSID }}"
          - name: INSTAGRAMCLIENTID
            value: "{{ .Values.INSTAGRAMCLIENTID }}"
          - name: INSTAGRAMCLIENTTOCKEN
            value: "{{ .Values.INSTAGRAMCLIENTTOCKEN }}"

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 90
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
