# Default values for stripebilling.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ottemo/stripebilling
  tag: 1
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  port: 80


STRIPEURL: stripe.ottemo.speroteck-dev.com
JURL: http://127.0.0.1:8080
JUSER: test:test
JSURL: http://127.0.0.1:8080
#HOST:
#PORT:
MHOST: 127.0.0.1
MPORT: 21
MUSER: test
MPASSWD: test
MFROM: test
MSUBJECT: test
#MFILE:

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
